access/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
]

mainapp/urls.py
from django.urls import path

from .views import *

app_name = 'mainapp'

urlpatterns = [
    path('', LandingPageView.as_view(), name='landing-page'),
    path('customer_list', CustomerListView.as_view(), name='customer-list'),
    path('customer_detail/<int:pk>', CustomerDetailView.as_view(), name='customer-detail'),

    path('order_list', OrderListView.as_view(), name='order-list'),
    path('customer_detail/<int:pk>/order_create', OrderCreateView.as_view(), name='order-create'),
    #path('customer_detail/<int:pk>/order_confirm', )

    path('product_list', ProductListView.as_view(), name='product-list'),
]

mainapp/models.py
import math

from django.db import models
from django.core.exceptions import ValidationError


class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество на складе')
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена')

    def __str__(self):
        return f"{self.name} ({self.quantity} шт.)"

    def clean(self):
        if self.quantity < 0:
            raise ValidationError('Недостаточно товара на складе')
        if self.price <= 0:
            raise ValidationError('Цена товара должна быть больше нуля')

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)


class Customer(models.Model):
    name = models.CharField(max_length=255, verbose_name='Фамилия')
    current_count = models.DecimalField(default=0, max_digits=7, decimal_places=2, verbose_name='Текущий счет')
    all_count = models.DecimalField(default=0, max_digits=7, decimal_places=2, verbose_name='Сумма покупок')
    credit_limit = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Потолок кредита')
    current_credit = models.DecimalField(default=0, max_digits=7, decimal_places=2, verbose_name='Текущий кредит')
    left_credit = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Остаток кредита')
    low_left_credit = models.BooleanField(default=False, editable=False, verbose_name='Низкий остаток кредита')
    comment = models.CharField(max_length=255, verbose_name='Комментарий')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.left_credit = self.credit_limit - self.current_credit
        if (self.left_credit * 10) < self.credit_limit:
            self.low_left_credit = True
        else:
            self.low_left_credit = False
        print(self.left_credit, self.credit_limit)
        print(self.low_left_credit)
        super().save(*args, **kwargs)


class Order(models.Model):
    pay_way_choices = (
        ('cash', 'Наличный расчет'),
        ('cashless', 'Безналичный расчет'),
        ('credit', 'Кредит'),
        ('barter', 'Бартер'),
        ('sell', 'Взаимозачет')
    )

    customer = models.ForeignKey(Customer, verbose_name='Покупатель', on_delete=models.CASCADE,
                                 related_name='orders')
    pay_way = models.CharField(max_length=255, choices=pay_way_choices, verbose_name='способ оплаты')
    needed_product = models.ForeignKey(Product, verbose_name='Запрашиваемый продукт', related_name='first_product',
                                       on_delete=models.CASCADE, blank=True, null=True)
    needed_quantity = models.PositiveIntegerField(verbose_name='Количество нужного товара', blank=True, null=True)
    needed_cost = models.DecimalField(default=0, max_digits=7, decimal_places=2,
                                      verbose_name='Стоимость нужного товара', blank=True, null=True)
    given_product = models.ForeignKey(Product, verbose_name='Отдаваемый продукт', related_name='second_product',
                                      on_delete=models.CASCADE, blank=True, null=True)
    given_quantity = models.PositiveIntegerField(verbose_name='Количество отдаваемого продукта',
                                                 blank=True, null=True)
    given_cost = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Стоимость отдаваемого продукта',
                                     blank=True, null=True)
    completed = models.BooleanField(default=False, verbose_name='Создан')

    def __str__(self):
        return f"{self.id} {self.customer.name} {self.pay_way}"

    def save(self, *args, **kwargs):
        # if self.pay_way == 'cash':
        #     self.needed_product.quantity -= self.needed_quantity
        #     self.needed_cost = self.needed_product.price * self.needed_quantity
        #     self.customer.all_count += self.needed_cost
        #     self.customer.save()
        #     self.needed_product.save()
        # elif self.pay_way == 'cashless':
        #     self.needed_product.quantity -= self.needed_quantity
        #     self.needed_cost = self.needed_product.price * self.needed_quantity
        #     if self.needed_cost <= self.customer.current_count:
        #         self.customer.current_count -= self.needed_cost
        #     else:   #   если денег на счету недостаточно
        #         self.pay_way = 'credit'
        #         self.customer.credit_count += self.needed_cost
        #     self.customer.all_count += self.needed_cost
        #     self.customer.save()
        #     self.needed_product.save()
        # elif self.pay_way == 'barter':
        #     self.needed_product.quantity -= self.needed_quantity
        #     self.needed_cost = self.needed_product.price * self.needed_quantity
        #     self.given_quantity = math.ceil(self.needed_cost / self.given_product.price)
        #     self.given_product.quantity += self.given_quantity
        #     self.given_cost = self.given_product.price * self.given_quantity
        #     self.needed_product.save()
        #     self.given_product.save()
        # elif self.pay_way == 'sell':
        #     self.given_cost = self.given_product.price * self.given_quantity
        #     self.given_product.quantity += self.given_quantity
        #     self.customer.current_credit -= self.given_cost
        #     self.customer.save()
        #     self.given_product.save()

        if self.pay_way != 'sell':
        # if (self.pay_way == 'cash') or (self.pay_way == 'cashless') or (self.pay_way == 'barter')
            self.needed_product.quantity -= self.needed_quantity
            self.needed_cost = self.needed_product.price * self.needed_quantity
            if (self.pay_way == 'cash') or (self.pay_way == 'cashless'):
                self.customer.all_count += self.needed_cost
                if self.pay_way == 'cashless':
                    if self.needed_cost <= self.customer.current_count:
                        self.customer.current_count -= self.needed_cost
                    else:   # если денег на счету недостаточно (мб стоит обнулить текущий счет и снизить )
                        self.pay_way = 'credit'
                        self.customer.credit_count += self.needed_cost - self.customer.current_count
                        self.customer.current_count = 0
            self.needed_product.save()
        if (self.pay_way == 'barter') or (self.pay_way == 'sell'):
            if self.pay_way == 'barter':
                self.given_quantity = math.ceil(self.needed_cost / self.given_product.price)
            self.given_product.quantity += self.given_quantity
            if self.pay_way == 'sell':
                self.given_cost = self.given_product.price * self.given_quantity
                if self.given_cost < self.customer.current_credit:
                    self.customer.current_credit -= self.given_cost
                else:
                    self.customer.current_count += self.given_cost - self.customer.current_credit
                    self.customer.current_credit = 0
            self.given_product.save()
        self.customer.save()
        super().save(*args, **kwargs)

templates/customer/customer_detail.html
{% extends 'base.html' %}

{% block title %}
    Информация о покупателе
{% endblock %}

{% block content %}
    <div class="w-full mb-4 py-6 justify-between item-center border-b border-gray-200">
        <h1 class="text-4xl text-gray-800">{{ customer.name }}</h1>
        <h2 class="title-font text-1xl font-medium text-gray-900">Текущий счет: <a class="text-green-800">{{ customer.current_count }}</a></h2>
        <h2 class="title-font text-1xl font-medium text-gray-900">Сумма покупок: <a class="text-green-800">{{ customer.all_count }}</a></h2>
        <h2 class="title-font text-1xl font-medium text-gray-900">Кредитный лимит: <a class="text-green-800">{{ customer.credit_limit }}</a></h2>
        <h2 class="title-font text-1xl font-medium text-gray-900">Текущий кредит: <a class="text-green-800">{{ customer.current_credit }}</a></h2>

            <h2 class="title-font text-1xl font-medium text-gray-900">Остаток по кредиту:
                {% if customer.low_left_credit %}
                    <a class="text-red-800">{{ customer.left_credit }}</a>
                {% else %}
                    <a class="text-green-800">{{ customer.left_credit }}</a>
                {% endif %}
            </h2>
        <h2 class="title-font text-1xl font-medium text-gray-900">Комментарий: <a class="text-green-800">{{ customer.comment }}</a></h2>
    </div>
    <div class="w-full mb-6 py-6 flex justify-between item-center">
        <div>
            <h1 class="text-3xl text-gray-800">Заказы покупателя</h1>
        </div>
        <div>
            <a class="text-red-800" href="{% url 'mainapp:order-create' customer.pk %}">Создать заказ</a>
        </div>
    </div>
    {% for order in orders %}
        <div class="w-full py-4">
            <h1 class="title-font text-2xl font-medium text-gray-900">Номер заказа: {{ order.id }}: {{ order.get_pay_way_display }}</h1>
            <h2 class="title-font text-1xl font-medium text-gray-900">Приобретенный товар:</h2>
            <p>{{ order.needed_product.name }} ({{ order.needed_quantity }} шт.) - {{ order.needed_cost }}</p>
            {% if order.pay_way == 'barter' %}
                <h2 class="title-font text-1xl font-medium text-gray-900">Обменяли на:</h2>
                <p><p>{{ order.given_product.name }} ({{ order.given_quantity }} шт.) - {{ order.given_cost }}</p>
                <h2 class="title-font text-1xl font-medium text-gray-900">Сумма покупки: {{ order.given_cost }} рублей</h2>
            {% else %}
                <h2 class="title-font text-1xl font-medium text-gray-900">Сумма покупки: {{ order.needed_cost }} рублей</h2>
            {% endif %}
        </div>
    {% endfor %}
{% endblock %}

templates/customer/customer_list.html
{% extends 'base.html' %}

{% block title %}
    Список покупателей
{% endblock %}

{% block content %}
    <div class="w-full mb-6 py-6 flex justify-between item-center border-b border-gray-200">
        <div>
            <h1 class="text-4xl text-gray-800">Покупатели</h1>
        </div>
        <div>
            <a class="text-red-800" href="#">Найти покупателя (или прямо сюда форму запихнуть?)</a>
        </div>
    </div>
    {% for customer in customers %}
        <div class="w-full py-6">
            <h1 class="title-font text-2xl font-medium text-gray-900">{{ customer.name }} - {{ customer.comment }}</h1>
            <p>Всего покупок на {{ customer.all_count }} рублей</p>
            <a class="text-red-800" href="{% url 'mainapp:customer-detail' customer.pk %}">Подробнее</a>
            <br>
        </div>
    {% endfor %}
{% endblock %}

templates/customer/customer_order_create.html
{% extends 'base.html' %}

{% block title %}
Создание заказа
{% endblock %}

{% block content %}
    <div class="w-full mb-4 py-6 justify-between item-center border-b border-gray-200">
        <h1 class="text-4xl text-gray-800">Создать заказ для клиента {{ customer.name }}</h1>
    </div>
    <form method="post" class="create-order" name="form">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="оформить заказ" class="inline-flex text-white bg-red-800 border-0 py-2 px-6 focus:outline-none hover:bg-red-900 rounded text-lg">
    </form>
{% endblock %}