access/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
]

mainapp/urls.py
from django.urls import path

from .views import *

app_name = 'mainapp'

urlpatterns = [
    path('', LandingPageView.as_view(), name='landing-page'),
    path('customer_list', CustomerListView.as_view(), name='customer-list'),
    path('customer_detail/<int:pk>', CustomerDetailView.as_view(), name='customer-detail'),

    path('order_list', OrderListView.as_view(), name='order-list'),
    path('customer_detail/<int:pk>/order_create', OrderCreateView.as_view(), name='order-create'),
    #path('customer_detail/<int:pk>/order_confirm', )

    path('product_list', ProductListView.as_view(), name='product-list'),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>
    <div class="max-w-4xl mx-auto bg-gray-100">
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock %}
    </div>
    {% include 'scripts.html' %}
</body>
</html>

templates/landing.html
{% extends 'base.html' %}

{% block title %}
    Landing page
{% endblock %}

{% block content %}
    <section class="text-gray-600 body-font">
        <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
            <div class="lg:w-2/3 w-full">
                <h1 class="text-center title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">ЗАДАНИЕ НА РАБОТУ</h1>

                <div class="text-left mb-8 leading-relaxed">
                    <h2 class="title-font text-2xl mb-4 font-medium text-gray-900">Разработать согласно требованиям и реализовать интерфейс автоматизированного рабочего места оператора по продажам для выполнения следующих действий:</h2>

                    <h3 class="title-font text-1xl mt-4 mb-2 font-medium text-gray-900">1. Ввод имени клиента, при вводе имени осуществляется поиск по списку клиентов, и если такой находится, то вывести:</h3>
                    <p>- общий счет покупок клиента (сумма всех покупок)</p>
                    <p>- текущий счет клиента (деньги на счету фирмы для покупок);</p>
                    <p>- потолок кредита (кредитный лимит, который не изменяется);</p>
                    <p>- текущий долг клиента;</p>
                    <p>- остаток кредита (разница между потолком кредита и текущим долгом);</p>
                    <p>- комментарий (о причине долга клиента, его надежности и т.п.).</p>
                    <p>Нужна таблица склада товаров.</p>

                    <h3 class="title-font text-1xl mt-4 mb-2 font-medium text-gray-900">2. Выбор вида продажи:</h3>
                    <p>- наличный расчет (увеличивается общий счет покупок клиента, остальные счета не изменяются, количество товаров уменьшается);</p>
                    <p>- безналичный расчет (увеличивается общий счет покупок клиента, уменьшается текущий счет клиента, остальные счета не изменяются, количество товаров уменьшается);</p>
                    <p>- кредит (увеличивается общий счет покупок клиента, увеличивается текущий долг клиента, уменьшается остаток кредита, текущий счет клиента в этом случае нулевой или недостаточный для покупки (во втором случае он должен быть учтен при покупке и обнулится), количество товаров уменьшается; при приближении текущего долга клиента к потолку кредита (90% от потолка кредита) подсвечивается красным текущий долг и остаток кредита; количество товаров уменьшается)</p>
                    <p>- бартер, т.е. обмен товаров без использования денег (никакие счета не изменяются, на складе количество одних товаров должно увеличиться,
                        количество других уменьшиться, стоимость товаров, количество которых увеличилось, должно быть равно стоимости товаров, количество которых уменьшилось);</p>
                    <p>- взаимозачет. (уменьшается текущий долг клиента, увеличивается остаток кредита, остальные счета не изменяются, количество товаров увеличивается).</p>

                    <h3 class="title-font text-1xl mt-4 mb-2 font-medium text-gray-900">3. Ввод перечня товаров и продаваемого количества в табличной части, с автоматическим указанием:</h3>
                    <p>- цены (из списка товаров);</p>
                    <p>- суммы за единицу;</p>
                    <p>- выводом текущего остатка.</p>
                    <p class="italic">§ Если введенное количество товаров меньше текущего остатка или равно ему, то цвет шрифта остатка должен быть одним (например, зеленым).</p>
                    <p class="italic">§ Если введенное количество товаров больше текущего остатка, то цвет шрифта остатка должен быть другим (например, красным), а также должно сработать звуковое предупреждение. (в случае наличия устройства воспроизведения звука)</p>
                    <p>4. Автоматический подсчет общей суммы купленных товаров для каждого клиента.</p>
                    <p>5. Формирование предупреждения, если общая сумма купленных товаров для клиента превышает потолок его кредита за минусом текущего долга клиента.</p>
                    <p>6. Формирование предупреждения если есть строки с незаполненным товаром, нулевой ценой и нулевым количеством.</p>
                </div>
                <div class="flex justify-center">
                    <button class="inline-flex text-white bg-red-800 border-0 py-2 px-6 focus:outline-none hover:bg-red-900 rounded text-lg">Понял</button>
                    <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">Понял</button>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/navbar.html
<header class="text-gray-600 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
        <a href="/" class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
            <img src="https://spectrasoft.ru/upload/iblock/1c9/1c959fd9decda0730104e8c3f4949092.png" width="40px">
            <span class="ml-3 text-xl">Access</span>
        </a>
        <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
                <a href="{% url 'mainapp:customer-list' %}" class="mr-5 hover:text-gray-900">Список покупателей</a>
                <a href="{% url 'mainapp:order-list' %}" class="mr-5 hover:text-gray-900">Список заказов</a>
                <a href="{% url 'mainapp:product-list' %}" class="mr-5 hover:text-gray-900">Список товаров</a>
        </nav>
    </div>
</header>

templates/scripts.html
{% load static %}

<script src="{% static 'js/main.js' %}">
</script>